In [6]:
import numpy as np

# ndarray.shape: Returns the dimensions of the array as a tuple.
my_lists = [[1,2,3], [4,5,6], [7,8,9]]
a = np.array(my_lists)
print(a)
# print(a.shape)

# my_list =  [[1,2,3], [4,5,6], [7,8,9]]
# my_list[0][0]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# ndarray.ndim: Returns the number of dimensions (axes) of the array.
print(a.ndim)

2


In [4]:
# ndarray.size: Returns the total number of elements in the array.
print(a.size)

9


In [5]:
# ndarray.dtype: Returns the data type of the elements in the array.
print(a.dtype)

int32


In [7]:
# ndarray.astype(): Changes the data type of the array to the specified type.
print(a.astype(float))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [8]:
# ndarray.flatten(): Returns a flattened copy of the array as a one-dimensional array.
print(a.flatten())

[1 2 3 4 5 6 7 8 9]


In [9]:
# ndarray.transpose(): Returns the transpose of the array (rows become columns and columns become rows)
print(a.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [17]:
# ndarray.reshape(): Returns a new array with the same data but a new shape.
my_lst = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]
b = np.array(my_lst)
print(b.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
# ndarray.sum(): Returns the sum of all elements in the array.
my_lst = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]
b = np.array(my_lst)
print(b.sum())

78


In [20]:
# ndarray.mean(): Returns the arithmetic mean of the array.
print(b.mean())

6.5


In [21]:
# ndarray.max(): Returns the maximum element of the array.
print(b.max())

12


In [22]:
print(b.min())

1


In [23]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [26]:
# 2 rows by 5 columns
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.linspace(0,3,8)

array([0.        , 0.42857143, 0.85714286, 1.28571429, 1.71428571,
       2.14285714, 2.57142857, 3.        ])

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
# return a 5 by 5 random matrices
np.random.rand(5,5)

array([[0.85735894, 0.42367806, 0.76447593, 0.9857424 , 0.51904928],
       [0.85341233, 0.61341425, 0.50977912, 0.32237068, 0.06116049],
       [0.52447722, 0.15243919, 0.28957926, 0.7075121 , 0.6685055 ],
       [0.4428217 , 0.15740103, 0.6598752 , 0.10167828, 0.91133891],
       [0.87170147, 0.8093015 , 0.43360578, 0.19058513, 0.17605777]])

In [34]:
np.random.randn(2)

array([-0.16363974, -0.20384498])

In [35]:
np.random.randn(4,4)

array([[-0.32010863, -0.38878412,  1.49912498, -0.55819928],
       [-1.49497278, -0.54954144, -0.78259301, -0.48401283],
       [ 1.8920154 ,  0.67119217,  1.10570048,  0.80543193],
       [-0.28027738, -0.71935672,  0.01765393, -1.11415196]])

In [39]:
# 1 is inclusive and 30 is not inclusive. return 5 of the item
np.random.randint(1,30,5)

array([ 7, 28,  3, 27, 23])

In [41]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
# numpy.transpose(): This method transposes an array.
print(np.transpose(a))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [44]:
# numpy.dot(): This method performs matrix multiplication between two arrays.
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result = np.dot(arr1, arr2)
print(result) 

[[19 22]
 [43 50]]


In [46]:
# =======================================================================================================================
# Numpy indexing and selection
# Array methods : ndim, shape,reshape,array,dtype, flatten, min,max,transpose,mean, arange

import numpy as np
arr = np.arange(0,13)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [47]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [48]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [49]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [52]:
# numpy array does broadcasting but list does not. Broadcast does a deep copy of the original array by providing a reference to the array.
# numpy can have copy specified
slice_arr = arr[0:6]
slice_arr[:] = 13
slice_arr

array([13, 13, 13, 13, 13, 13])

In [53]:
arr

array([13, 13, 13, 13, 13, 13,  6,  7,  8,  9, 10, 11, 12])

In [54]:
arr_copy = arr.copy()
arr_copy

array([13, 13, 13, 13, 13, 13,  6,  7,  8,  9, 10, 11, 12])

In [55]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [56]:
arr

array([13, 13, 13, 13, 13, 13,  6,  7,  8,  9, 10, 11, 12])

In [57]:
# Indexing a 2D array(matrix)
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [58]:
# How to grab an item in an array: double and single bracket format
# arr_2d[row-index][column-index]- DOUBLE BRACKET FORMAT
arr_2d[0][1]

10

In [59]:
arr_2d[0]

array([ 5, 10, 15])

In [60]:
arr_2d[1][0]

20

In [61]:
arr_2d[2][2]

45

In [62]:
# SINGLE FORMAT
arr_2d[1,2]

30

In [63]:
arr_2d[0,0]

5

In [64]:
# Slice some matrices or sections of the array
# Grab row 0 to 1 and column 1 to end
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [65]:
arr_2d[:1,:2]

array([[ 5, 10]])

In [66]:
arr_2d[:3,:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [67]:
arr_2d[1:, 1:]

array([[25, 30],
       [40, 45]])

In [69]:
arr_2d[1:, :2]

array([[20, 25],
       [35, 40]])

In [70]:
arr_2d[1:, :3]

array([[20, 25, 30],
       [35, 40, 45]])

In [74]:
new_2d = np.array([[1,2,5,3,9,4],[10,14,16,11,12,17],[23,28,29,22,21,26], [31,35,38,30,39,30], [41,46,42,40,43,49], [50,52,59,51,50,57], [69,63,62,65,67,68]])
new_2d

array([[ 1,  2,  5,  3,  9,  4],
       [10, 14, 16, 11, 12, 17],
       [23, 28, 29, 22, 21, 26],
       [31, 35, 38, 30, 39, 30],
       [41, 46, 42, 40, 43, 49],
       [50, 52, 59, 51, 50, 57],
       [69, 63, 62, 65, 67, 68]])

In [75]:
new_2d[:4, :5]

array([[ 1,  2,  5,  3,  9],
       [10, 14, 16, 11, 12],
       [23, 28, 29, 22, 21],
       [31, 35, 38, 30, 39]])

In [76]:
new_2d[3:6, :3]

array([[31, 35, 38],
       [41, 46, 42],
       [50, 52, 59]])

In [77]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [79]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [80]:
arr[arr<4]

array([1, 2, 3])

In [86]:
new_2d = np.arange(40).reshape(4,10)[:3, :3].flatten()[new_2d < 12]
new_2d

array([ 0,  1,  2, 10, 11])

In [87]:
# Numpy array with array operations.
# Numpy arrays have several operations such as basic operations as seen above and others such as arrays basic maths
# ARRAY MULPLICATION
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 4, 6, 8, 10])

mult_arr = arr1 * arr2
mult_arr

array([ 2,  8, 18, 32, 50])

In [88]:
# ARRAY ADDITION
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 4, 6, 8, 10])

add_arr = arr1 + arr2
add_arr

array([ 3,  6,  9, 12, 15])

In [89]:
#ARRAY SUBTRACTION 
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 4, 6, 8, 10])
sub_arr = arr1 - arr2
sub_arr

array([-1, -2, -3, -4, -5])

In [90]:
# ARRAY DIVISION
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 4, 6, 8, 10])

div_arr = arr1 / arr2
div_arr

array([0.5, 0.5, 0.5, 0.5, 0.5])

In [91]:
# DOT OPERATION
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 4, 6, 8, 10])

dot_arr = np.dot(arr1, arr2)
dot_arr

110

In [93]:
# NUMPY ARRAY ERROR CHECKS WITH ZEROS
arr3 = np.array([0,1,1,2,0])
arr3 / arr3

C:\Users\pc\AppData\Local\Temp\ipykernel_15280\3673077617.py:3: RuntimeWarning: invalid value encountered in divide
  arr3 / arr3


array([nan,  1.,  1.,  1., nan])

In [94]:
# ARRAYS WITH EXPONENTS
arr3**2

array([0, 1, 1, 4, 0])

In [95]:
sqrt_arr = np.sqrt(arr2)
sqrt_arr

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766])

In [96]:
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [98]:
np.cos(arr2)

array([-0.41614684, -0.65364362,  0.96017029, -0.14550003, -0.83907153])

In [99]:
np.tan(arr3)

array([ 0.        ,  1.55740772,  1.55740772, -2.18503986,  0.        ])

In [100]:
np.max(arr1)

5

In [101]:
np.min(arr2)

2

In [102]:
# NUMPY EXERCISES
import numpy as np

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [103]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [106]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [108]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [110]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [111]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [112]:
np.array([[0,1,2], [3,4,5], [6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [113]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [115]:
np.random.randn(5,5)

array([[ 0.15620237, -0.41741347, -1.04261867, -0.94722812, -0.66442882],
       [-0.03917772,  0.13255585, -0.90917404,  0.30120114,  2.89456933],
       [ 0.11868232,  0.36806962, -0.64984079,  0.4999678 ,  0.43259527],
       [ 1.11656791,  0.73270765, -0.90163393, -0.79915063,  1.15283356],
       [ 1.61893123, -0.45388603,  0.09072191,  0.39354734,  0.79169893]])

In [116]:
np.random.rand(100).round(2)

array([0.65, 0.2 , 0.93, 0.69, 0.76, 0.74, 0.22, 0.5 , 0.6 , 0.85, 0.06,
       0.26, 0.3 , 0.98, 0.28, 0.58, 0.99, 0.05, 0.36, 0.83, 0.68, 0.99,
       0.38, 0.9 , 0.23, 0.16, 0.25, 0.49, 0.9 , 0.55, 0.43, 0.64, 0.77,
       0.51, 0.53, 0.39, 0.97, 0.87, 0.45, 0.79, 0.26, 0.18, 0.43, 0.44,
       0.7 , 0.41, 0.7 , 0.52, 0.9 , 0.33, 0.69, 0.81, 0.13, 0.75, 0.57,
       0.29, 0.71, 0.95, 0.62, 0.35, 0.57, 0.54, 0.17, 0.37, 0.21, 0.62,
       0.36, 0.41, 0.8 , 0.74, 0.04, 0.37, 0.35, 0.36, 0.74, 0.36, 0.54,
       0.41, 0.04, 0.28, 0.01, 0.31, 0.32, 0.91, 0.07, 0.35, 0.65, 0.96,
       0.11, 0.62, 0.46, 1.  , 0.76, 0.12, 0.01, 0.91, 0.22, 0.77, 0.51,
       0.77])

In [117]:
np.random.rand(20)

array([0.58144019, 0.22446056, 0.28894812, 0.92138453, 0.373868  ,
       0.50290833, 0.74971399, 0.907528  , 0.67305447, 0.04363688,
       0.02789436, 0.29441019, 0.16952792, 0.90551838, 0.81594894,
       0.42136073, 0.10590198, 0.39908842, 0.97422476, 0.53912504])

In [118]:
mat = np.arange(1, 26).reshape(5,5)

In [119]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [120]:
# mat[index : length]
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [122]:
mat[4,4]

25

In [127]:
mat[:3, 1]

array([ 2,  7, 12])

In [128]:
mat[4]

array([21, 22, 23, 24, 25])

In [129]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [130]:
mat.sum()

325

In [131]:
mat.std()

7.211102550927978

In [140]:
# axis= 0 means 0 as rows and axis=1 means 1 as columns. So sum of all numbers in rows or columns
col_sum = np.sum(mat, axis=1)
col_sum

array([ 15,  40,  65,  90, 115])