In [1]:
food_amount = [20, 10, 32, 41.2, 60]
food_items = ['mango juice', 'Pepper', 'Tomato Paste', 'Eggs', 'Soaps']

food_list = dict(zip(food_items, food_amount))
food_list

{'mango juice': 20,
 'Pepper': 10,
 'Tomato Paste': 32,
 'Eggs': 41.2,
 'Soaps': 60}

In [2]:
food_list.items()

dict_items([('mango juice', 20), ('Pepper', 10), ('Tomato Paste', 32), ('Eggs', 41.2), ('Soaps', 60)])

In [3]:
food_list.values

<function dict.values>

In [6]:
food_list.keys()

TypeError: 'dict_keys' object is not subscriptable

In [7]:
food_list.values()

dict_values([20, 10, 32, 41.2, 60])

In [9]:
for items, amt in food_list.items():
    print(items, amt)

mango juice 20
Pepper 10
Tomato Paste 32
Eggs 41.2
Soaps 60


In [12]:
# Numpy and methods
import numpy as np
array = np.arange(0,15)

In [13]:
# array[index:length]
array[:6]

array([0, 1, 2, 3, 4, 5])

In [14]:
array[0:5]

array([0, 1, 2, 3, 4])

In [15]:
array[8:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [20]:
# Numpy broadcasting (array[:]): broadcasting make a deep copy of the part of a code to the original code base
# Numpy arrays accepts homogenous integer objects
sliced_array = array[:7]
sliced_array[:] = 22
sliced_array

array([22, 22, 22, 22, 22, 22, 22])

In [18]:
array

array([22, 22, 22, 22, 22, 22, 22,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
# Arrays are by rows and columns

TypeError: data type 'banaja' not understood

In [28]:
my_arr = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]
b = np.array(my_arr)
print(b.shape)
# print(b.reshape(3,4))

(4, 3)


In [29]:
print(b[0][2])

3


In [31]:
print(b.max())

12


In [33]:
print(b.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [34]:
list_items = [1,2,3,4,5,6,7]
print(list_items)

[1, 2, 3, 4, 5, 6, 7]


In [35]:
print(list_items.max)

AttributeError: 'list' object has no attribute 'max'

In [39]:
list_i = [[1,2,3], [4,5,6], [7,8,9]]
print(list_i)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [58]:
import time

start_time = time.time()
for x in list_i:
    for y in x:
        if(y == 7):
            print(f'{y} found')
end_time = time.time()
elapsed_time = end_time - start_time

print("Elapsed time: ", elapsed_time, "seconds")


7 found
Elapsed time:  0.003986835479736328 seconds


In [55]:
arr_i = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr_i

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
start_time = time.time()
arr_i[2][0]
end_time = time.time()
elapsed_time = end_time - start_time

print("Elapsed time: ", elapsed_time, "seconds")

Elapsed time:  0.001161336898803711 seconds
